### ISSUE TITLE
Czech & Slovak translation?

### ISSUE THREAD

**Issue by LukasRada** [emesik/dont-buy-monero-sticker#1]
Hi,
this is awesome idea of stickers :)

Can you make one with CZ & SK translation please?

**Comment by emesik** [comment]
Sure, if you provide texts.

**Comment by LukasRada** [comment]
OK

CZ:
NEKUPUJ
Kryptoměny škodí bankovnímu systému a mohou oslabit statní aparát

SK:
NEKUPUJ
Kryptomeny škodí bankovnému systému a môžu oslabiť štátný aparát

**Comment by emesik** [comment]
Added. Thanks!
