### ISSUE TITLE
Is this repo still maintained? 

### ISSUE THREAD

**Issue by erciccione** [emesik/dont-buy-monero-sticker#17]
@emesik if not, i would be happy to take care of it.

**Comment by emesik** [comment]
Hi,
I'm too busy recently to take care of it on regular basis. I've added you to collaborators, so you should have write permissions right now. If you need anything more, just ask. Thanks!

**Comment by erciccione** [comment]
Perfect. Thank you :)

**Comment by erciccione** [comment]
@emesik I'm having problems with the vector file. Looks like it's not possible to edit the text even if the font is installed, it looks converted into graphic paths. Should i just replace the text with a new box containing the new text, or is there a cleaner way to work on the file?

**Comment by emesik** [comment]
The text is converted to curves to avoid problems when people don't have the required font. It makes translations a bit complicated, but anyway for each language version you'll have to adjust the text size and formatting a bit, if you want it to look good.

My approach was:
1. copy the file,
2. remove old text,
3. create new text box and adjust formatting,
4. convert to curves,
5. save,
6. export PNG

**Comment by erciccione** [comment]
Got it. Thanks for the clarification :)
