### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by shinjinishiyama** [emesik/dont-buy-monero-sticker#3]
DON'T BUY MONERO
モネロを買わないで

Cryptocurrencies are harmful to the banking system
暗号通貨は銀行システムにとって有害であり

and may weaken the state apparatus
国家組織を弱体化させるおそれがあります

**Comment by emesik** [comment]
Can we split the first line to keep to original layout of the sticker? If I see correctly, モネロ means Monero. Is it possible to reverse the order and keep "don't buy" part first, or it would be grammatically incorrect?

Or perhaps the logo could go to the top, and the sentence be placed below it.

What do you think?

**Comment by shinjinishiyama** [comment]
Yes, モネロ means Monero.

> Is it possible to reverse the order and keep "don't buy" part first, or it would be grammatically incorrect?

It's kinda difficult; if one forced it, it would read rather awkward.

Why does the order need to be that way? It seems perfectly OK to me to have the line with モネロを above the logo and the rest below.

**Comment by emesik** [comment]
Well, actually you're right. It seems I was making simple things complex ;)

**Comment by emesik** [comment]
I've just added the images. Please check if they are OK. My knowledge of Japanese is none, I even have no idea where it's allowed to break lines.

If anything is wrong, please let me know.

**Comment by shinjinishiyama** [comment]
Cool!
Let me suggest some corrections:

- Below the logo: 買わないで (currently "で" is missing)
- 3rd line in the box: 国家組織を弱体化させる
- Last line in the box: おそれがあります

**Comment by emesik** [comment]
Please check if it's OK now.

**Comment by shinjinishiyama** [comment]
Perfect! Thank you :)
