### ISSUE TITLE
SVG text displayed black

### ISSUE THREAD

**Issue by egodigitus** [emesik/dont-buy-monero-sticker#4]
Had a problem with the svg text being displayed as black. I converted the text to path. The result worked for me. Unfortunately I can not upload an *.svg to a git issue.

**Comment by emesik** [comment]
Which one?

Text should be path in all versions. If it's not somewhere, it's a bug.

**Comment by egodigitus** [comment]
The english version ( dont-buy-monero-sticker/sticker.en.svg ) opened with gimp displays like this: https://imgur.com/a/x5BDq

**Comment by emesik** [comment]
My GIMP opens it without problems. For SVG I recommend Inkscape, which will export a bitmap in whatever dimensions you wish.
