### ISSUE TITLE
Irish Translation

### ISSUE THREAD

**Issue by umma08** [emesik/dont-buy-monero-sticker#7]
Any chance of getting an Irish translation on this? I tired myself, but seeing as the alphabet isn't in this repository, i didn't know how to complete....

Ná cenneach 
(Don’t buy)

Dhéanann airgead-cripteagrafaíocht damáiste go dí córas na bainc agus go dí an stáit. 
(Cryptocurrencies are harmful to the banking system and may weaken state apparatus)

**Comment by emesik** [comment]
Added in #9
