### ISSUE TITLE
[Proposal] transfer this repository to the Monero Ecosystem

### ISSUE THREAD

**Issue by erciccione** [emesik/dont-buy-monero-sticker#8]
Hi! i'm collecting some of the best repositories about Monero in one single place, the [Monero Ecosystem project](https://github.com/monero-ecosystem). Would be great to have also this repository. Everything will be the same for youand you'll still be the maintainer as before, but you will get the shiny Monero Ecosystem badge on github. You can find more infos on the [meta repository](https://github.com/monero-ecosystem/meta). Let me know!

**Comment by emesik** [comment]
Sounds good. How do we proceed?

**Comment by erciccione** [comment]
Perfect! I'm adding you as a member of the project, then you can go to your repository -> settings and click on "transfer repo" -> "monero-ecosystem"

**Comment by erciccione** [comment]
Repo is transferred, closing this issue. Thanks!
